# Generated by Django 5.0 on 2024-01-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dbproject',
            fields=[
                ('auto_field', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
