# Generated by Django 5.0 on 2024-01-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbproject',
            name='big_integer_field',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dbproject',
            name='binary_field',
            field=models.BinaryField(default=b'\x01\x02\x03\x04'),
        ),
        migrations.AddField(
            model_name='dbproject',
            name='boolean_field',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dbproject',
            name='char_field',
            field=models.CharField(default='Fahim', max_length=255),
        ),
    ]
