# Generated by Django 5.0 on 2024-01-04 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0003_dbproject_comma_separated_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbproject',
            name='date_field',
            field=models.DateField(default=datetime.date(2024, 1, 4)),
        ),
        migrations.AddField(
            model_name='dbproject',
            name='decimal_field',
            field=models.DecimalField(decimal_places=2, default=123.24, max_digits=5),
        ),
        migrations.AddField(
            model_name='dbproject',
            name='duration_field',
            field=models.DurationField(default=datetime.timedelta(days=7, seconds=45000)),
        ),
    ]
