# Generated by Django 5.0 on 2024-01-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0004_dbproject_date_field_dbproject_decimal_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbproject',
            name='date_field',
        ),
        migrations.AddField(
            model_name='dbproject',
            name='file_field',
            field=models.FileField(default='files/default_file.txt', upload_to='files/'),
        ),
    ]
