# Generated by Django 5.0 on 2024-01-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0005_remove_dbproject_date_field_dbproject_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbproject',
            name='generic_ip_address_field',
            field=models.GenericIPAddressField(default='192.168.1.1'),
        ),
        migrations.AddField(
            model_name='dbproject',
            name='json_field',
            field=models.JSONField(default=dict),
        ),
    ]
