# Generated by Django 5.0 on 2024-01-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0006_dbproject_generic_ip_address_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_ip_address_field', models.GenericIPAddressField(default='192.168.1.1')),
                ('json_field', models.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='dbproject',
            name='generic_ip_address_field',
        ),
        migrations.RemoveField(
            model_name='dbproject',
            name='json_field',
        ),
    ]
