# Generated by Django 5.0 on 2024-01-04 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0007_modelone_remove_dbproject_generic_ip_address_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbproject',
            name='decimal_field',
        ),
        migrations.RemoveField(
            model_name='dbproject',
            name='duration_field',
        ),
        migrations.RemoveField(
            model_name='dbproject',
            name='file_field',
        ),
        migrations.RemoveField(
            model_name='modelone',
            name='json_field',
        ),
        migrations.AddField(
            model_name='modelone',
            name='decimal_field',
            field=models.DecimalField(decimal_places=2, default=123.24, max_digits=5),
        ),
        migrations.AddField(
            model_name='modelone',
            name='duration_field',
            field=models.DurationField(default=datetime.timedelta(days=7, seconds=45000)),
        ),
        migrations.AddField(
            model_name='modelone',
            name='file_field',
            field=models.FileField(default='files/default_file.txt', upload_to='files/'),
        ),
        migrations.AddField(
            model_name='modelone',
            name='float_field',
            field=models.FloatField(default=0.0),
        ),
    ]
