# Generated by Django 5.0 on 2024-01-06 05:20

import musician.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicians',
            name='Phone_number',
            field=models.CharField(max_length=11, validators=[musician.models.validate_phone_number_length]),
        ),
    ]
