# Generated by Django 5.0 on 2024-01-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task_description',
            field=models.TextField(),
        ),
    ]
