# Generated by Django 5.0 on 2024-01-07 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCategory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcategory',
            old_name='TaskModel',
            new_name='task_model',
        ),
    ]
